Container name is non-deterministic

diff --git a/.github/workflows/build-test-e2e.yml b/.github/workflows/build-test-e2e.yml
--- a/.github/workflows/build-test-e2e.yml
+++ b/.github/workflows/build-test-e2e.yml
@@ -61,7 +61,6 @@ jobs:
       matrix:
         shard: [1/3, 2/3, 3/3]
     env:
-      CONTAINER_NAME: 'swc-e2e-tomcat'
       CI: true
       DESTINATION_BUCKET: e2e-reports-bucket-bucket-1p1qz6p48t4uy
       REPORT_ID: ${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt }}
@@ -78,6 +77,9 @@ jobs:
           path: ${{ env.BUILD_DIR }}
       - name: Install pnpm
         uses: pnpm/action-setup@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: ${{ env.NODE_VERSION }}
       - name: Run app containers
         run: pnpm docker:start
       - uses: actions/setup-node@v4
@@ -93,28 +95,20 @@ jobs:
             echo "::error:: downloaded WAR not found at expected location"
             exit 1
           fi
-          if [[ $(docker ps --filter "name=${{ env.CONTAINER_NAME }}" --format '{{.Names}}') != "${{ env.CONTAINER_NAME }}" ]]; then
-            echo "::error:: SWC docker container is not running"
-            exit 1
-          fi
-          if ! docker port "${{ env.CONTAINER_NAME }}" | grep -q "8080/tcp -> 0.0.0.0:8888"; then
-              echo "::error:: SWC container configuration does not specify expected port mapping"
-              exit 1
-          fi
-          if [[ "$(docker exec "${{ env.CONTAINER_NAME }}" bash -c "curl -sS -o /dev/null -w '%{http_code}\n' http://127.0.0.1:8080")" != "200" ]]; then
-            echo "::error:: SWC container port not accessible from container"
-            exit 1
-          fi
-          if [[ "$(docker exec "${{ env.CONTAINER_NAME }}" bash -c "curl -sS -o /dev/null -w '%{http_code}\n' http://172.17.0.1:8888")" != "200" ]]; then
-            echo "::error:: SWC host port not accessible from container"
-            exit 1
-          fi
           if ! netstat -an | grep -q "8888"; then
             echo "::error:: host is not listening to SWC host port"
             exit 1
           fi
+          if ! netstat -an | grep -q "3000"; then
+            echo "::error:: host is not listening to SageAccountWeb host port"
+            exit 1
+          fi
           if [[ "$(curl -w '%{http_code}' --output /dev/null --silent --fail --show-error http://127.0.0.1:8888 2>&1)" != "200" ]]; then
             echo "::error:: SWC host port not accessible from host"
+            exit 1
+          fi
+          if [[ "$(curl -w '%{http_code}' --output /dev/null --silent --fail --show-error http://127.0.0.1:3000 2>&1)" != "200" ]]; then
+            echo "::error:: SageAccountWeb host port not accessible from host"
             exit 1
           fi
       - name: Run Playwright tests
